### ISSUE TITLE
Tiny bug

### ISSUE THREAD

**Issue by dbd5** [tunecino/yii2-nested-rest#1]
Hi,

Great work, this looks promising indeed!

Under Configuration, there's a typo in tokens, should be:

 'tokens' **=>** [ /\* optional _/
            '{id}' => '<id:\d[\d,]_>',
            '{IDs}' => 'IDs:\d[\d,]*',
], 

Instead of;

 'tokens' = [ /\* optional _/
            '{id}' => '<id:\d[\d,]_>',
            '{IDs}' => 'IDs:\d[\d,]*',
], 

A

**Comment by tunecino** [comment]
yes its a typo in the README file. I'll fix it tonight thanks for reporting @dbd5

**Comment by tunecino** [comment]
fixed in 0.2.0 thanks
