### ISSUE TITLE
"count(): Parameter must be an array or an object that implements Countable"

### ISSUE THREAD

**Issue by rondey** [tunecino/yii2-nested-rest#10]
Hello, when I call a url like this: 'GET http://localhost:8080/authors/1/books/1' I get this error:
`{
    "name": "PHP Warning",
    "message": "count(): Parameter must be an array or an object that implements Countable",
    "code": 2,
    "type": "yii\\base\\ErrorException",
    "file": "/srv/http/restapi/vendor/tunecino/yii2-nested-rest/src/Action.php",
    "line": 113,
    "stack-trace": [
        "#0 [internal function]: yii\\base\\ErrorHandler->handleError(2, 'count(): Parame...', '/srv/http/resta...', 113, Array)",
        "#1 /srv/http/restapi/vendor/tunecino/yii2-nested-rest/src/Action.php(113): count(Object(app\\models\\Book))",
        "#2 /srv/http/restapi/vendor/tunecino/yii2-nested-rest/src/ViewAction.php(28): tunecino\\nestedrest\\Action->findCurrentModels('1')",
        "#3 [internal function]: tunecino\\nestedrest\\ViewAction->run('1')",
        "#4 /srv/http/restapi/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)",
        "#5 /srv/http/restapi/vendor/yiisoft/yii2/base/Controller.php(157): yii\\base\\Action->runWithParams(Array)",
        "#6 /srv/http/restapi/vendor/yiisoft/yii2/base/Module.php(528): yii\\base\\Controller->runAction('nested-view', Array)",
        "#7 /srv/http/restapi/vendor/yiisoft/yii2/web/Application.php(103): yii\\base\\Module->runAction('book/nested-vie...', Array)",
        "#8 /srv/http/restapi/vendor/yiisoft/yii2/base/Application.php(386): yii\\web\\Application->handleRequest(Object(yii\\web\\Request))",
        "#9 /srv/http/restapi/web/index.php(12): yii\\base\\Application->run()",
        "#10 {main}"
    ]
}`

The $model is this:
`object(app\models\Book)#134 (10) {
  ["_attributes":"yii\db\BaseActiveRecord":private]=>
  array(4) {
    ["id"]=>
    int(1)
    ["name"]=>
    string(23) "Il Signore degli Anelli"
    ["genre"]=>
    string(7) "Fantasy"
    ["author_id"]=>
    int(1)
  }
  ["_oldAttributes":"yii\db\BaseActiveRecord":private]=>
  array(4) {
    ["id"]=>
    int(1)
    ["name"]=>
    string(23) "Il Signore degli Anelli"
    ["genre"]=>
    string(7) "Fantasy"
    ["author_id"]=>
    int(1)
  }
  ["_related":"yii\db\BaseActiveRecord":private]=>
  array(0) {
  }
  ["_relationsDependencies":"yii\db\BaseActiveRecord":private]=>
  array(0) {
  }
  ["_errors":"yii\base\Model":private]=>
  NULL
  ["_validators":"yii\base\Model":private]=>
  NULL
  ["_scenario":"yii\base\Model":private]=>
  string(7) "default"
  ["_events":"yii\base\Component":private]=>
  array(0) {
  }
  ["_eventWildcards":"yii\base\Component":private]=>
  array(0) {
  }
  ["_behaviors":"yii\base\Component":private]=>
  array(0) {
  }
}
`

So counting an object is impossibile. My, horrible, fix was this in line 113 in /src/Action.php : 
`        if ($model === null or count($ids) > 1 and count($model) !== count($ids)) `
I hope you will find a better fix.

Cheers

**Comment by tunecino** [comment]
Should be fixed in v0.4.0 release. Thanks for reporting and sorry for delay.
