### ISSUE TITLE
Trying to get it to work

### ISSUE THREAD

**Issue by dbd5** [tunecino/yii2-nested-rest#2]
I've done the following;
1. Installed as instructed with composer.
2. Placed **public function actions(){...}** verbatim inside my ApiController because all controllers inherit from it.
3. Added a section to my urlManager rules array (reproduced below)

I expect GET http://localhost/api/web/v1/testpapers/133/testquestions to fetch the list of questions in testpaper 133 and http://localhost/api/web/v1/testpapers/133/testquestions/id to fetch a particular question in testpaper 133, but I get {"name":"Not Found","message":"Page not found.","code":0,"status":404,"type":"yii\web\NotFoundHttpException"}

There is of course an existing 1 to many relationship between testpaper and testquestions. 
Could you take a look and advise what I could be missing. Perhaps this will be an actual example that will help others configure their setup correctly if we can get it to work.

All GET requests work except the nested related requests

Regards,

Adam

---

```
        'rules' => [
            // Based on Yii defaults UrlRule class
            [
                'class' => 'yii\rest\UrlRule',
                'controller' => [
                    'v1/apiuser',
                    'v1/question',
                    'v1/testconfig',
                    'v1/testpaper',
                    'v1/testquestions',
                ],
                'tokens' => [
                    '{id}' => '<id:\\w+>'
                ],
            ],

            // Based on tunecino's collection of helper actions and a custom UrlRule class
            // https://github.com/tunecino/yii2-nested-rest
            [
                // the custom UrlRule (required)
                'class' => 'tunecino\nestedrest\UrlRule',

                // the model class name (required)
                'modelClass' => 'api\common\models\Testpaper',

                // relations names to be nested with this model they should be already
                // defined in the model class. (required)
                'relations' => ['user','testquestions'],

                // used to generate the 'prefix'. default: the model name pluralized (optional)
                // 'resourceName' => 'players',
                'resourceName' => 'testquestions',

                // building related rules using 'controller => ['teams' => 'v1/team']'
                // instead of 'controller => ['team']' (optional)
                'modulePrefix' => 'v1',

                // the default list of patterns. they may all be overridden here or just edited
                // within $only, $except and $extraPatterns properties (optional)
                'patterns' => [
                    'GET,HEAD {IDs}' => 'nested-view',
                    'GET,HEAD' => 'nested-index',
                    'POST' => 'nested-create',
                    'PUT {IDs}' => 'nested-link',
                    'DELETE {IDs}' => 'nested-unlink',
                    'DELETE' => 'nested-unlink-all',
                    '{id}' => 'options',
                    '' => 'options',
                ],

            ],
        ],
```

**Comment by tunecino** [comment]
thanks for reporting this @dbd5 
can you please show how the `testquestions` relation is defined inside your model ?

I'm using those 2 Yii helpers to get the model name:

``` php
$modelName = Inflector::camel2id(StringHelper::basename($this->modelClass));
```

Also same for the relation name, so as example, in case your model look like this:

``` php
class TestPaper extends ActiveRecord
{
    public function getTestQuestions()
    {
        return $this->hasMany(TestQuestion::className(), ['testpaper_id' => 'id']);
    }
```

then the related url should be like this:

`http://localhost/api/web/v1/test-papers/133/test-questions`

**Comment by tunecino** [comment]
It may also be the foreign key. If your model class name is `Testpaper` and the foreign key is different from `testpaper_id` (by default is `$modelName . '_id'`) then you also need to add the one you are using to rules within the ~~resourceName attribute~~ linkAttribute property.

**Comment by dbd5** [comment]
Here's an extract of the testpaper model with all relationsships;

/**
- This is the model class for table "{{%testpaper}}".
  *
  ...
- @property Testconfig $testconfig
- @property User $user
- @property Testquestions[] $testquestions
  */
  class Testpaper extends \yii\db\ActiveRecord
  {
  ...
  public function getTestconfig()
  {
      return $this->hasOne(Testconfig::className(), ['id' => 'testconfig_id']);
  }
  
  public function getUser()
  {
      return $this->hasOne(User::className(), ['id' => 'user_id']);
  }
  
  public function getTestquestions()
  {
      return $this->hasMany(Testquestions::className(), ['testpaper_id' => 'id']);
  }
  ...
  }

**Comment by tunecino** [comment]
@dbd5 model looks good. according to your configurations this is the yii/rest/UrlRule object that should be generated by this extension:

```
Array
(
    [class] => yii\rest\UrlRule
    [patterns] => Array
        (
            [GET,HEAD {IDs}] => nested-view
            [GET,HEAD] => nested-index
            [POST] => nested-create
            [PUT {IDs}] => nested-link
            [DELETE {IDs}] => nested-unlink
            [DELETE] => nested-unlink-all
            [{id}] => options
            [] => options
        )

    [prefix] => testquestions/<testpaper_id:\d+>
    [controller] => Array
        (
            [testquestions] => v1/testquestion
        )
)
```

So there is already an error with with the `resourceName`. it should be `'resourceName' => 'testpapers'` instead of `'resourceName' => 'testquestions'`. can you set it to `testquestions` ? (or just comment that line as by default it will be set to the model name pluralized any way) then tell me please if it works.

**Comment by dbd5** [comment]
Hi @tunecino ,

Still didn't work after I changed 'resourceName' => 'testquestions' to 'resourceName' => 'testpapers'.
Do you want me to add the following?

```
[prefix] => testquestions/<testpaper_id:\d+>
[controller] => Array
    (
        [testquestions] => v1/testquestion
    )
```

**Comment by tunecino** [comment]
no that is the auto generated code by this extension. can you try please `'resourceName' => 'v1/testpapers'` instead ?

**Comment by dbd5** [comment]
Now it gives the following error;

{"name":"Not Found","message":"Page not found.","code":0,"status":404,"type":"yii\web\NotFoundHttpException","previous":{"name":"Invalid Route","message":"Unable to resolve the request \"v1/testquestion/nested-index\".","code":0,"type":"yii\base\InvalidRouteException"}}

**Comment by tunecino** [comment]
mmm I see. this should be because of this [line](https://github.com/tunecino/yii2-nested-rest/blob/e8b3356f1aa77e3c1bd64eb57ca7bb3987bd484e/src/UrlRule.php#L166). by default it is expected by this extension that a relation called `testquestions` should be mapped to a controller named `TestquestionController` instead of `TestquestionsController`. I'll make it more customizable this weekend to cover similar cases to yours. For the moment I think it will only work if you change your controller name to `TestquestionController`

**Comment by dbd5** [comment]
Oh good catch - the one time I did not follow the convention, now it's clear - thanks. Will wait for the change but if you think it's better to enforce the convention, happy to go along as well.

Another question - to what depth does the nesting work, hypothetically will you support something like;
http://localhost/api/web/v1/testconfigs/10/testpapers/133/testquestions/id1/answers/id2/users

A

**Comment by tunecino** [comment]
@dbd5 try to upgrade to version 0.2.0 by setting `"tunecino/yii2-nested-rest": "*"` in the require section of your composer.json file and doing `$ composer update`. If every thing is OK it should work now with those rules configs:

``` php
[
    'class' => 'tunecino\nestedrest\UrlRule',
    'modelClass' => 'api\common\models\Testpaper',
    'relations' => [
        'user',
        'testquestions' => 'testquestions' // relation => controller
    ],
    'modulePrefix' => 'v1',
    'resourceName' => 'v1/testpapers',
],
```

About the other question, currently it supports only 2 levels. but yes I'm planning to make it support requests like `GET /testconfigs/10/testpapers/133/testquestions/1/answers/2/users`
But this will be done in a future release as I get enough time to figure out a good way to achieve it without allowing navigation where we are not authorized to.
