### ISSUE TITLE
Maybe a bug

### ISSUE THREAD

**Issue by Spground** [tunecino/yii2-nested-rest#3]
Hi, i am using the `yii2-nested-rest`, which is awesome. 
Unfortunately i got `404` result after i config my config file as the document。I traced log and read the source code. 
Here is my config:

```
 [
                    // The custom UrlRule class
                    'class' => 'api\modules\v1\common\nestedrest\UrlRule',
                    'modelClass' => 'api\modules\v1\models\CourseXchgInfo',
                    'relations' => ['courseXchgs' => ['courses' => 'course-exchange'] ],
                    'resourceName' => 'exchanges',
                    'modulePrefix' => 'v1',
                    'linkAttribute' => 'course_xchg_info_id',
                ]
```

and here is my log point, which is at about line 188 in `UrlRule.php` file 

`Yii::getLogger()->log($routeObj, Logger::LEVEL_INFO, "====");`

I made the below request, and got the request result  `404`.

`http://api.duthelper.com/v1/exchanges/3/courses/5`

then i got the log info

```
[
    'class' => 'yii\\rest\\UrlRule',
    'patterns' => [
        'GET,HEAD {IDs}' => 'nested-view',
        'GET,HEAD' => 'nested-index',
        'POST' => 'nested-create',
        'PUT {IDs}' => 'nested-link',
        'DELETE {IDs}' => 'nested-unlink',
        'DELETE' => 'nested-unlink-all',
        '{id}' => 'options',
        '' => 'options',
    ],
    'tokens' => [
        '{id}' => '<id:\\d[\\d,]*>',
        '{IDs}' => '<IDs:\\d[\\d,]*>',
    ],
    'prefix' => 'exchanges/<course_xchg_info_id:\\d+>',
    'controller' => [
        'courses' => 'v1/course-exchange',
    ],
]
F:\www\duthelper\api\modules\v1\common\nestedrest\UrlRule.php (184)
```

As log info shown,  everything is ok but 'prefix' => 'exchanges/<course_xchg_info_id:\\d+>',, which can not  match `v1/exchanges/3` of  `http://api.duthelper.com/v1/exchanges/3/courses/5`.

Although i specified  'modulePrefix' => 'v1', it did not work for me.

Below is your source code  at about line 162 in `UrlRule.php` file 
`$this->config['prefix'] = $resourceName . '/<' .$link_attribute. ':\d+>';`
i think it should be $this->config['prefix'] =( isset($this->modulePrefix) ? $this->modulePrefix .'/' : '').$resourceName . '/<' .$link_attribute. ':\d+>';

Now, i modified my config file as below without changing your source code 

```
 [
                    // The custom UrlRule class
                    'class' => 'api\modules\v1\common\nestedrest\UrlRule',
                    'modelClass' => 'api\modules\v1\models\CourseXchgInfo',
                    'relations' => ['courseXchgs' => ['courses' => 'course-exchange'] ],
                    'resourceName' => 'v1/exchanges',
                    'modulePrefix' => 'v1', 
                    'linkAttribute' => 'course_xchg_info_id',
                ]
```

Finally, it worked for me.

So i made PR about the bug(maybe). Thanks.

**Comment by tunecino** [comment]
I'll check it against different cases when I'll be home next weekend. thanks @Spground for reporting it and  thanks for the PR.

**Comment by tunecino** [comment]
@Spground I checked it and I think it is not a bug. the way you did set your 2d configurations is the correct way to handle it because `modulePrefix` has no relation with url structure, it is related to the module name holding your controller so it's only role is to tell the app under which namespace the controller could be found.

There is cases where even with versioned rest your don't want to specify that version in the url like just:

```
http://api.duthelper.com/exchanges/3/courses/5
```

but still you need to tell the app that the related controller is hosted under a `v1` module:

``` php
'controller' => [
    'courses' => 'v1/course-exchange',
],
```

and that is where you only set `modulePrefix`.

**Comment by tunecino** [comment]
To better explain it, here is a more advanced example: 

imagine you have multiple versions of `v1` under different modules like maybe:

```
v1-alpha-0
v1-alpha-0.1
v1-beta-1.32
```

and you want user to get redirected to the last released controller of the `v1` version when specified in url. and to make it even more complexe, you want to follow [jsonapi spec](http://jsonapi.org/format/#fetching-relationships) by including that `relationships` word into url. well this is how your configs may look like in that case:

``` php
[
    'class' => 'tunecino\nestedrest\UrlRule',
    'modelClass' => 'api\modules\v1\models\CourseXchgInfo',
    'relations' => ['courseXchgs' => ['relationships/courses' => 'course-exchange'] ],
    'resourceName' => 'v1/exchanges',
    'modulePrefix' => 'v1-beta-1.32', 
    'linkAttribute' => 'course_xchg_info_id',
]
```

and that should make a url like:

```
http://api.duthelper.com/v1/exchanges/3/relationships/courses
```

to redirect to to the controller holded under the `v1-beta-1.32` module:

``` php
...
'prefix' => 'v1/exchanges/<course_xchg_info_id:\\d+>',
'controller' => [
    'courses' => 'v1-beta-1.32/course-exchange',
],
```
