### ISSUE TITLE
Work together with default yii\rest\UrlRule

### ISSUE THREAD

**Issue by RdeWilde** [tunecino/yii2-nested-rest#5]
Can you please eleborate how this custom URL rule would work together with the default yii\rest\UrlRule implementation? I tried to implement this custom rule, but the previous default endpoints from yii\rest stopped working. I did inherit the actions though (merge).

Any good info on this? Climbing up wrong tree, do I need two seperate rules?

**Comment by tunecino** [comment]
> do I need two seperate rules?

exactly. the idea is to define rules for single endpoints using the default `yii\rest\UrlRule` as described in Yii official documentation. The custom URLRule class introduced in this extension should be used to nested urls only. so it should be defined as a separate rule like shown in the README file:

``` php
'rules' => [
    [
        // Yii defaults REST UrlRule class
        'class' => 'yii\rest\UrlRule',
        'controller' => ['team','player'],
    ],
    [
        // The custom UrlRule class
        'class' => 'tunecino\nestedrest\UrlRule',
        'modelClass' => 'app\models\Team',
        'relations' => ['players'],
    ],
]
```

Here the first rule is as described in Yii documentation, will create [those endpoints](http://www.yiiframework.com/doc-2.0/guide-rest-quick-start.html#trying-it-out) for `/teams` and `/players`.

The second rule is using the custom one to define related patterns to `/teams/{id}/players` and `/teams/{id}/players/{IDs}`.

>  I did inherit the actions though (merge)

Also be sure to not override [default ActiveController's actions](https://github.com/yiisoft/yii2/blob/master/framework/rest/ActiveController.php#L70-L104) inside your controller. this extension should use different naming for its nested related actions. those will be merged with default ones and that is why by default they are expected to be named as follow:

``` php
public function actions() 
{
    $actions = parent::actions(); 
    $actions['nested-index'] = [...];
    $actions['nested-view'] = [... ];
    $actions['nested-create'] = [... ];
    ...
```

**Comment by RdeWilde** [comment]
Perfectly clear, thanks for explaining. We got this working (just needed to use a slashed resourceName to fool the prefix/basepath) ;-) Really nice!
