### ISSUE TITLE
Stuck on routing

### ISSUE THREAD

**Issue by Skalin** [tunecino/yii2-nested-rest#9]
Hello,

I have followed both the issues that were here containing information about routing, nevertheless I also can't figure the routing out on the latest version.

Coud you please show me what am I doing wrong?

At the current moment, I have the game table and server table. One game can have many servers, one server can be assigned to one game.

My routes are following:

```
	[
		'class' => 'yii\rest\UrlRule',
		'controller' => ['v1/game','v1/server'],
	],
	[
		'class' => 'tunecino\nestedrest\UrlRule',
		'resourceName' => 'v1/games',
		'modulePrefix' => 'v1',
		'modelClass' => 'app\modules\v1\models\Game',
		'relations' => ['servers'],
	],
	[
		'class' => 'tunecino\nestedrest\UrlRule',
		'resourceName' => 'v1/servers',
		'modulePrefix' => 'v1',
		'modelClass' => 'app\modules\v1\models\Server',
		'relations' => ['game']
	],
```

I can access the /v1/games and /v1/servers, nevertheless, I can't access /v1/games/ID/servers, the website throws 404.

The game model has this relation setted up, and the corresponding hasOne relation is set up in Server model:
``
	public function getServers()
	{
		return $this->hasMany(Server::className(), ['game_id' => 'id']);
	}
``

Is there anything else I am missing please?

**Comment by tunecino** [comment]
Sorry for delay. Your configurations looks correct to me. Did you add the related actions like `nested-index` to your controller as shown in the 2d part of [configuration section](https://github.com/tunecino/yii2-nested-rest#configuration)?
